name: Pull Request
description: This is a PR template, maybe
title: "[Pull Request]: "
labels: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the new Pull Request.
      placeholder: This introduces, fixes, etc.
    validations:
      required: true
  - type: textarea
    id: closing
    attributes:
      label: Closes
      description: What issues does it close?
      placeholder: "Closes #420, #69"
    validations:
      required: true
