name: Bug Report
description: Tell us about unexpected behavior from LÖVE Potion.
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
  id: description
  attributes:
    label: What happened?
    description: Describe the Bug.
    placeholder: A bug happened!
  validations:
    required: true
  - type: textarea
  id: expected
  attributes:
    label: What was expected?
    description: Describe what should happen.
  validations:
    required: true
  - type: textarea
  id: code
  attributes:
    label: Code to reproduce
    description: Please provide a **minimal** code sample. For big snippets, use a service such as pastebin.
    render: lua
  validations:
    required: true
